# site infomation
site_name: Backlight Wiki
site_description: Backlight'S personal wiki
site_author: Backlight
site_url: https://backl1ght.github.io
strict: true

repo_name: Backlight Wiki
repo_url: https://github.com/Backl1ght/Backl1ght.github.io

# settings
theme:
  name: material
  custom_dir: "mkdocs-material/material"
  palette:
    primary: 'white'
    accent: 'red'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  language: 'zh'
  favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

copyright: 'Copyright &copy; Backlight'

extra_javascript:
  # - '_static/js/extra.js'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  # - '_static/css/extra.css'

extra:
  search:
    language: 'jp'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# navigation
nav:
  - 主页:
    - 你好，世界: index.md
    - 简介: index/intro.md
    - 作者: index/author.md
  - 测试:
    - 代码高亮测试: test/code-test.md
    - 数学公式测试: test/math-test.md
    - 脚注测试: test/footnotes-test.md